

services:
  configserver:
    image: "rahat1722/configserver:section6"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail http://localhost:8071/actuator/health || exit 1"
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - eazybank

  accounts:
    image: "rahat1722/accounts:section6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - eazybank
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default

  loans:
    image: "rahat1722/loans:section6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - eazybank
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default

  cards:
    image: "rahat1722/cards:section6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - eazybank
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default

networks:
  eazybank:
    driver: "bridge"