services:

  accountsDB:
    container_name: accountsDB
    ports:
      - "5432:5432"
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansDB:
    container_name: loansDB
    ports:
      - "5433:5432"
    extends:
      file: common-config.yml
      service: microservice-db-config


  cardsDB:
    container_name: cardsDB
    ports:
      - "5434:5432"
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "rahat1722/configserver:section7"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    #    depends_on:
    #      rabbit:
    #        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

    extends:
      file: common-config.yml
      service: microservice-base-config
  #    deploy:
  #      resources:
  #        limits:
  #          memory: "700m"
  #    networks:
  #      - eazybank

  accounts:
    image: "rahat1722/accounts:section7"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_DATASOURCE_URL: "jdbc:postgresql://accountsDB:5432/postgres"
    depends_on:
      accountsDB:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-config-server-config
  #    depends_on:
  #      configserver:
  #        condition: service_healthy
  #    deploy:
  #      resources:
  #        limits:
  #          memory: "700m"
  #    networks:
  #      - eazybank
  #    environment:
  #      SPRING_APPLICATION_NAME: accounts
  #      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  #      SPRING_PROFILES_ACTIVE: default

  loans:
    image: "rahat1722/loans:section7"
    container_name: loans-ms
    ports:
      - "8090:8090"
    #    depends_on:
    #      configserver:
    #        condition: service_healthy
    #    deploy:
    #      resources:
    #        limits:
    #          memory: "700m"
    #    networks:
    #      - eazybank
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_DATASOURCE_URL: "jdbc:postgresql://loansDB:5432/postgres"
    #      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
    #      SPRING_PROFILES_ACTIVE: default
    depends_on:
      loansDB:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-config-server-config


  cards:
    image: "rahat1722/cards:section7"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_DATASOURCE_URL: "jdbc:postgresql://cardsDB:5432/postgres"
    #      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
    #      SPRING_PROFILES_ACTIVE: default
    depends_on:
      cardsDB:
        condition: service_healthy
    #    depends_on:
    #      configserver:
    #        condition: service_healthy
    #    deploy:
    #      resources:
    #        limits:
    #          memory: "700m"
    #    networks:
    #      - eazybank
    extends:
      file: common-config.yml
      service: microservice-config-server-config

networks:
  eazybank:
    driver: "bridge"